# Generated by Django 3.1.2 on 2021-08-24 03:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region_name', models.CharField(default='Unknown', help_text="<strong>Region's canonical name .</strong>", max_length=50)),
            ],
        ),
    ]
