# Generated by Django 3.1.2 on 2021-08-25 12:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', help_text="<strong>Datasource's canonical name.</strong>", max_length=50)),
            ],
            options={
                'db_table': 'datasource',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', help_text="<strong>Region's canonical name .</strong>", max_length=50)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_trip_origin_coordinates', django.contrib.gis.db.models.fields.PointField(help_text='<strong>Tuple representation of lat lon of trip origin.</strong>', srid=4326)),
                ('_trip_destination_coordinates', django.contrib.gis.db.models.fields.PointField(help_text='<strong>Tuple representation of lat lon of trip destination.</strong>', srid=4326)),
                ('trip_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='<strong>Date and time when the trip was conducted.</strong>')),
                ('data_source', models.ForeignKey(help_text="<strong>Datasource's uuid.</strong>", on_delete=django.db.models.deletion.PROTECT, to='trip_business.datasource')),
                ('region', models.ForeignKey(help_text="<strong>Region's uuid.</strong>", on_delete=django.db.models.deletion.PROTECT, to='trip_business.region')),
            ],
            options={
                'db_table': 'trip',
            },
        ),
    ]
