# Generated by Django 3.1.2 on 2021-08-24 03:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trip_business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('datasource_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datasource_name', models.CharField(default='Unknown', help_text="<strong>Datasource's canonical name.</strong>", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_origin_coordinates', django.contrib.gis.db.models.fields.PointField(help_text='<strong>Tuple representation of lat lon of trip origin.</strong>', srid=4326)),
                ('trip_destination_coordinates', django.contrib.gis.db.models.fields.PointField(help_text='<strong>Tuple representation of lat lon of trip destination.</strong>', srid=4326)),
                ('trip_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='<strong>Date and time when the trip was conducted.</strong>')),
                ('data_source', models.ForeignKey(help_text="<strong>Datasource's uuid.</strong>", on_delete=django.db.models.deletion.PROTECT, to='trip_business.datasource')),
                ('region', models.ForeignKey(help_text="<strong>Region's uuid.</strong>", on_delete=django.db.models.deletion.PROTECT, to='trip_business.region')),
            ],
        ),
    ]
