# Generated by Django 3.1.2 on 2021-08-25 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trip_business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='id',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
