# Generated by Django 3.1.2 on 2021-08-24 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_business', '0002_datasource_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='datasource_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='datasource',
            old_name='datasource_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region_name',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='datasource',
            table='datasource',
        ),
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
        migrations.AlterModelTable(
            name='trip',
            table='trip',
        ),
    ]
