# Generated by Django 3.1.2 on 2021-08-24 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_business', '0003_auto_20210823_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trip_destination_coordinates',
            new_name='_trip_destination_coordinates',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_origin_coordinates',
            new_name='_trip_origin_coordinates',
        ),
    ]
