# Generated by Django 3.2.5 on 2021-08-23 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
    ]
