# Generated by Django 3.2.5 on 2021-08-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction_manager', '0002_alter_file_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='temp/'),
        ),
    ]
