# Generated by Django 3.2.5 on 2021-08-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction_manager', '0003_alter_file_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'managed': False},
        ),
    ]
