# Generated by Django 3.2.5 on 2021-08-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_extraction_manager', '0005_alter_file_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'managed': False},
        ),
    ]
